import sqlite3
conn = sqlite3.connect('training.db')

c = conn.cursor()

# Create table
c.execute("CREATE TABLE STUDENT(ROLLNO INT PRIMARY KEY NOT NULL,NAME TEXT NOT NULL,REGDNO INT NOT NULL,ADDRESS CHAR(50));")

c.execute("CREATE TABLE COURSE(COURSENO INT PRIMARY KEY NOT NULL,COURSENAME TEXT NOT NULL,PRICE INT NOT NULL,DESCRIPTION CHAR(50));")

c.execute("CREATE TABLE EMPLOYEE(EMPNO INT PRIMARY KEY NOT NULL,ENAME TEXT NOT NULL,AGE INT NOT NULL,ADDRESS CHAR(50));")

c.execute("CREATE TABLE COURSE_STD_reg(CSID INT PRIMARY KEY NOT NULL,COURSEID INT,STUDENTID INT, FOREIGN KEY(COURSEID) REFERENCES COURSE(COURSENO),FOREIGN KEY(STUDENTID) REFERENCES STUDENT(ROLLNO));")

c.execute("CREATE TABLE COURSE_EMPLOYEE_reg(CEID INT PRIMARY KEY NOT NULL,COURSEID INT, EMPLOYEEID INT, FOREIGN KEY(COURSEID) REFERENCES COURSE(COURSENO),FOREIGN KEY(EMPLOYEEID) REFERENCES EMPLOYEE(EMPNO));")


conn.close()
