import sqlite3
conn=sqlite3.connect('training.db')
c=conn.cursor()
r=int(input("please enter the roll no."))
ua=str(input('enter new value of address'))
conn.execute("UPDATE STUDENT SET ADDRESS='%s' WHERE ROLLNO==%d" % (ua,r))
print('updated successfully student')
conn.commit()
e=int(input("please enter the empno no."))
ea=str(input('enter new value of address'))
conn.execute("UPDATE EMPLOYEE SET ADDRESS='%s' WHERE EMPNO==%d" % (ea,e))
print('updated successfully employee')
conn.commit()
c=int(input("please enter the course no."))
p=int(input('enter new value of description'))
conn.execute("UPDATE COURSE SET DESCRIPTION='%s' WHERE COURSENO==%d" % (p,c))
print('updated successfully course')
conn.commit()
